apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whereami
  name: whereami
  namespace: whereami
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      - env:
        - name: ECHO_HEADERS
          value: "True"
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.24
        imagePullPolicy: IfNotPresent
        name: whereami
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whereami
  name: whereami
  namespace: whereami
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: whereami
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whereami
  namespace: whereami
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: "*.dev.tausight.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whereami
            port:
              number: 80
  - host: "svc.internal.dev.tausight.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whereami
            port:
              number: 80
